openapi: 3.0.3
info:
  title: Sample REST-based API
  description: |-
    This is a sample RESTful api on a given resource 'my-resource'.
  version: 1.0.11
externalDocs:
  description: REST
  url: https://it.wikipedia.org/wiki/Representational_state_transfer
tags:
  - name: my-resource
    description: Everything about my-resource
paths:
  /my-resource:
    get:
      tags:
        - my-resource
      summary: Get a list of all resources
      operationId: getAllResources
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyResource'
    post:
      tags:
        - my-resource
      summary: Create a new resource
      operationId: createNewResource
      requestBody:
        description: Create a new resource
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyResourceUpload'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResource'
        '500':
          description: Internal Server Error - failed to create new resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The details of the error
                required: 
                  - message

  /my-resource/{id}:
    get:
      tags:
        - my-resource
      summary: Get details about one resource
      description: Get details about one resource by Id
      operationId: getResourceDetails
      parameters:
        - name: id
          in: path
          description: ID of resource to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResource'
        '400':
          description: Invalid ID supplied (format is not UUID)
        '404':
          description: ID not found
    put:
      tags:
        - my-resource
      summary: Update one resource
      description: Update one resource by Id
      operationId: updateResource
      parameters:
        - name: id
          in: path
          description: ID of resource to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: The new resource state
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyResourceUpload'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResource'
        '400':
          description: Invalid ID supplied (format is not UUID)
        '404':
          description: ID not found
    delete:
      tags:
        - my-resource
      summary: Delete one resource
      description: Delete one resource by Id
      operationId: deleteResource
      parameters:
        - name: id
          in: path
          description: ID of resource to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResource'
        '400':
          description: Invalid ID supplied (format is not UUID)
        '404':
          description: ID not found

components:
  schemas:
    MyResource:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "c6278aad-9a32-4d0f-8312-3adef587d503"
        first-value:
          type: integer
          format: int64
          example: 42
        second-value:
          type: string
          example: "anystring"
      required: 
        - id
        - first-value
        - second-value
    MyResourceUpload:
      type: object
      properties:
        first-value:
          type: integer
          format: int64
          example: 42
        second-value:
          type: string
          example: "anystring"
      required:
        - first-value
        - second-value
